spring:
  application:
    name: Name of project

  datasource:
    url: *url to database
    username: username for database
    password: password for database
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

